eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 8083
spring:
  application:
    name: service-sales
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: psUTlZerOfwp1wur
    url: jdbc:mysql://talent-engine.c0dlb3x026bd.us-east-1.rds.amazonaws.com:3306/dragon-integrador?useSSL=false&serverTimezone=UTC
    username: dragon-user
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
